# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FooPls' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'SwiftKeychainWrapper'
  pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'KakaoOpenSDK/KakaoOpenSDK'
  pod 'SDWebImage'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'JTAppleCalendar'
  pod 'Kingfisher'
  pod 'RAMAnimatedTabBarController'
  pod 'FirebaseUI/Storage'
  # Pods for FooPls

end
